name: Lint and Format
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
      - name: Install Packages
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
      - name: Install Packages
        run: npm ci --ignore-scripts
      - name: Typecheck
        run: npm run typecheck
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
      - name: Install Packages
        run: npm ci --ignore-scripts
      - name: Format
        run: npm run format
